### ISSUE TITLE
Update bazarr.conf

### ISSUE THREAD

**Issue by angrycuban13** [organizrTools/Config-Collections-for-Nginx#13]
Please update bazarr.conf to include a trailing `\` when specifying the location.

**Comment by jrdnlc** [comment]
So `location /bazarr/` ?

**Comment by angrycuban13** [comment]
Actually, we might need to modify the conf as follows:

`proxy_pass http://127.0.0.1:6767/bazarr;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header Host $http_host;
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_http_version 1.1;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "Upgrade";
 proxy_redirect off;`

There was someone in the support channel that copied the conf directly from here and it wouldn't work. After adding those additional headers it worked. 

Not sure about the trailing `/` as it didn't work for him.

**Comment by jrdnlc** [comment]
Looks like Bazarr updated their nginx conf. Compared it to the one they have and updated it. Thanks
