### ISSUE TITLE
Third party app compatibility with Rutorrent subdirectory RP

### ISSUE THREAD

**Issue by JohanSF** [organizrTools/Config-Collections-for-Nginx#5]
For now I have a separate Rutorrent subdomain RP running with basic auth so that I can use the android app Transdroid with it. It would be nice to close this vulnerability once and for all, perhaps using a similar method as you have for sonarr/radarr/lidarr.

Kind Regards, Johan

**Comment by gilbN** [comment]
nvm, I should read first.

**Comment by HalianElf** [comment]
You would need to address this to ruTorrent. We can only do what the app itself has. There's no magic way to create an API endpoint in an NGINX config.
