### ISSUE TITLE
Third party app compatibility with Booksonic subdirectory RP

### ISSUE THREAD

**Issue by JohanSF** [organizrTools/Config-Collections-for-Nginx#6]
For now I have a separate Booksonic subdomain RP running with basic auth so that I can use the android app by the same name Booksonic with it. It would be nice to close this vulnerability once and for all, perhaps using a similar method as you have for sonarr/radarr/lidarr.

Kind Regards, Johan

**Comment by HalianElf** [comment]
Same thing goes for this one. You would need to get Booksonic to address this.
